### ISSUE TITLE
[Feature] Ability to edit selected page

### ISSUE THREAD

**Issue by Nithe14** [deepanchal/dnote-tui#37]
## Description
The ability to edit selected page would be nice to have.

## Screenshots
N/A
## Suggested tasks
- [ ] Add keybinding `e` to open selected page in default editor

**Comment by deepanchal** [comment]
Yes, I ran into limitations using ratatui's simple template for building TUI. I am changing the project structure to use component template. I have a work in progress branch which I will merge soon. But, that feature is coming soon along with other write related features :)

**Comment by deepanchal** [comment]
I will try to get this feature released in `0.4.0`
